using System.Diagnostics;

using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Cache;

using TrueUnleveledSkyrim.Config;
using TrueUnleveledSkyrim.Patch;


namespace TrueUnleveledSkyrim
{
    public class Patcher
    {
        // Default seed, used by the legacy Randomizer below. The real seed comes from the RandomSeed setting.
        private const int DefaultSeed = 0x54555331;

        // Kept only so existing callers still compile. It is seeded, but its output depends on call order, so prefer RandomFor().
        [Obsolete("Depends on processing order. Use Patcher.RandomFor(formKey) for reproducible results.")]
        public static readonly Random Randomizer = new(DefaultSeed);

        internal static Lazy<TUSConfig> ModSettings = null!;

        // Snapshot of the load order *before* this patch. Records generated by the patch are deliberately not visible through it.
        // Use state.LinkCache when you need to see records created or changed by the patch itself.
        internal static ILinkCache LinkCache { get; private set; } = null!;

        // Returns a random generator whose sequence only depends on the record (and an optional salt), not on processing order.
        // The same load order therefore always produces the same patch, even if records are processed in a different order.
        internal static Random RandomFor(FormKey key, string salt = "")
        {
            unchecked
            {
                // FNV-1a. string.GetHashCode() is randomized per process, so it can't be used here.
                uint hash = 2166136261;
                foreach (char c in key.ToString() + salt)
                {
                    hash ^= c;
                    hash *= 16777619;
                }

                return new Random((int)hash ^ ModSettings.Value.RandomSeed);
            }
        }

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(nickname: "Mod Settings", path: "settings.json", out ModSettings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "TUS.esp")
                .Run(args);
        }

        // Runs a patch stage and reports how long it took, including when it fails.
        private static void RunStage(string name, Action stage)
        {
            Console.WriteLine($"=== {name} ===");
            var timer = Stopwatch.StartNew();
            try
            {
                stage();
            }
            catch
            {
                Console.WriteLine($"=== {name} FAILED after {timer.Elapsed.TotalSeconds:F1}s ===");
                throw;
            }

            Console.WriteLine($"=== {name} finished in {timer.Elapsed.TotalSeconds:F1}s ===\n");
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            var settings = ModSettings.Value;

            LinkCache = state.LoadOrder.PriorityOrder.ToImmutableLinkCache();
            GeneratedRecords.Clear();
            CustomPerksPatcher.Reset();
            SpellDistributor.Reset();

            TUSConstants.GetPaths(state);

            // Stage order matters: NPCs look up the weak/strong leveled lists and outfits generated by the item stages,
            // and outfits look up the generated leveled lists.
            if (settings.UnlevelItems)
            {
                RunStage("Leveled item lists", () => LeveledItemsPatcher.PatchLVLI(state));
                RunStage("Outfits", () => OutfitsPatcher.PatchOutfits(state));
            }

            if (settings.UnlevelNPCs)
            {
                // Must run before the NPC stage, which hands out the duplicated custom perks.
                if (settings.NPCs.UseCustomPerkTrees && settings.NPCs.NPCPerksPerLevel > 0)
                    RunStage("Custom perk trees", () => CustomPerksPatcher.PatchCustomPerks(state));

                RunStage("NPCs", () => NPCsPatcher.PatchNPCs(state));
            }

            if (settings.UnlevelZones)
            {
                RunStage("Encounter zones", () => ZonesPatcher.PatchZones(state));
            }

            if (settings.RebalanceEquipment)
            {
                RunStage("Equipment rebalance", () => ItemsPatcher.PatchItems(state));
            }
        }
    }
}
