using System.Diagnostics.CodeAnalysis;

using Mutagen.Bethesda.Skyrim;

namespace TrueUnleveledSkyrim.Patch
{
    /// <summary>
    /// Index of the weak/strong record variants generated by the patcher, keyed by EditorID.
    /// Replaces scanning PatchMod.LeveledItems / PatchMod.Outfits with a linear search for every lookup.
    /// </summary>
    internal static class GeneratedRecords
    {
        private static readonly Dictionary<string, LeveledItem> leveledItemsByEditorId = new(StringComparer.Ordinal);
        private static readonly Dictionary<string, Outfit> outfitsByEditorId = new(StringComparer.Ordinal);
        private static readonly List<(LeveledItem Item, string Postfix)> generatedLeveledItems = new();

        public static IReadOnlyList<(LeveledItem Item, string Postfix)> GeneratedLeveledItems => generatedLeveledItems;

        public static void Clear()
        {
            leveledItemsByEditorId.Clear();
            outfitsByEditorId.Clear();
            generatedLeveledItems.Clear();
        }

        public static void RegisterLeveledItem(LeveledItem item, string postfix)
        {
            if (item.EditorID is null)
                return;

            leveledItemsByEditorId[item.EditorID] = item;
            generatedLeveledItems.Add((item, postfix));
        }

        public static void RegisterOutfit(Outfit outfit)
        {
            if (outfit.EditorID is null)
                return;

            outfitsByEditorId[outfit.EditorID] = outfit;
        }

        // Finds the generated variant (named baseEditorId + postfix) of a leveled list.
        public static bool TryGetLeveledItem(string? baseEditorId, string postfix, [MaybeNullWhen(false)] out LeveledItem item)
        {
            if (baseEditorId is null)
            {
                item = default;
                return false;
            }

            return leveledItemsByEditorId.TryGetValue(baseEditorId + postfix, out item);
        }

        // Finds the generated variant (named baseEditorId + postfix) of an outfit.
        public static bool TryGetOutfit(string? baseEditorId, string postfix, [MaybeNullWhen(false)] out Outfit outfit)
        {
            if (baseEditorId is null)
            {
                outfit = default;
                return false;
            }

            return outfitsByEditorId.TryGetValue(baseEditorId + postfix, out outfit);
        }
    }
}
